### ISSUE TITLE
App crashes when use consumer inside RefreshIndicator

### ISSUE THREAD

**Issue by beiger** [rrousselGit/provider#425]
Here is my code:
```dart
class TestPage extends StatefulWidget {
        @override
        TestPageState createState() => TestPageState();
}

class TestPageState extends State<TestPage> {
	TestModel testModel;
        @override
         Widget build(BuildContext context) {
                 return ChangeNotifierProvider<TestModel>.value(
		        value: testModel,
	                child: Scaffold(
		                appBar: AppBar(
			                 title: Text(''),
			        ),
			        body: RefreshIndicator(
				         onRefresh: () async{
				                testModel.addIndex();
				         },
				        child: CustomScrollView(
					        slivers: [
						        _sliver()
					        ],
				        ),
			        ),
	                ),
                );
        }
  
        Widget _sliver() {
  	        return Consumer<TestModel>(
	                builder: (context, model, child) {
		                if (model.index % 2 == 0) {
			                return SliverFillRemaining(
				                child: Icon(Icons.threed_rotation),
			                );
		                } else {
			                return SliverPadding(
				                padding: EdgeInsets.fromLTRB(4, 40, 4, 4),
				                sliver: SliverList(
					                delegate: SliverChildBuilderDelegate(
							        (BuildContext context, int index) {
							                return Container(height: 100, color: Colors.green,);
						                },
							        childCount: 20
					                ),
				                ),
			                );
		                }
	                },
                );
        }
  
        @override
        void initState() {
	        super.initState();
	        testModel = TestModel();
        }
	
        @override
        void dispose() {
	        super.dispose();
        }
}

class TestModel extends ChangeNotifier {
	int _index = 0;
	
	void addIndex() {
		_index++;
		notifyListeners();
	}
	
	int get index => _index;
}
```

crash info:
```java
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1573 pos 12: 'center.parent == this': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      RenderViewport.indexOfFirstChild (package:flutter/src/rendering/viewport.dart:1573:12)
#3      RenderViewportBase.debugDescribeChildren (package:flutter/src/rendering/viewport.dart:853:17)
#4      DiagnosticableTreeNode.getChildren (package:flutter/src/foundation/diagnostics.dart:2977:20)
#5      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1555:32)
#6      DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1596:6)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by beiger** [comment]
When I pull to refresh the page, app crashed.

**Comment by smiLLe** [comment]
I think it is because you change your state synchronously in ```onRefresh```.

**Comment by beiger** [comment]
If I change to this:
```dart
class TestPageState extends State<TestPage> {
	TestModel testModel;
	@override
	Widget build(BuildContext context) {
		return ChangeNotifierProvider<TestModel>.value(
			value: testModel,
			child: Scaffold(
				appBar: AppBar(
					title: Text(''),
				),
				body: RefreshIndicator(
					onRefresh: () async{
						testModel.addIndex();
						setState(() {
						  
						});
					},
					child: CustomScrollView(
						slivers: [
							_sliver()
						],
					),
				),
			),
		);
	}
	
	Widget _sliver() {
		if (testModel.index % 2 == 0) {
			return SliverFillRemaining(
				child: Icon(Icons.threed_rotation),
			);
		} else {
			return SliverPadding(
				padding: EdgeInsets.fromLTRB(4, 40, 4, 4),
				sliver: SliverList(
					delegate: SliverChildBuilderDelegate(
									(BuildContext context, int index) {
								return Container(height: 100, color: Colors.green,);
							},
							childCount: 20
					),
				),
			);
		}
	}
	
	@override
	void initState() {
		super.initState();
		testModel = TestModel();
	}
	
	@override
	void dispose() {
		super.dispose();
	}
}
```
It is ok.

**Comment by rrousselGit** [comment]
Closing since it was resolved

**Comment by beiger** [comment]
This problem still exists.
Consumer, RefreshIndicator, CustomScrollView, SliverPadding， Using these components at the same time causes problems.
